# Generated by Django 4.0.1 on 2022-01-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
